#!/usr/bin/env python3
"""
show_queue.py - Read schedule.yaml (as generated by plan_passes.py) and print
the approved pass queue, same filtering run_passes.py uses.

Usage:
    python3 show_queue.py
    python3 show_queue.py --all        # include unapproved / rejected passes too
    python3 show_queue.py --path schedule.yaml
"""

import argparse
import sys
from datetime import datetime, timezone

try:
    import yaml
except ImportError:
    print("PyYAML not installed. Run: pip3 install pyyaml", file=sys.stderr)
    sys.exit(1)


def get_first(d, keys, default=None):
    """Return the first present, non-None value among a list of candidate keys."""
    for k in keys:
        if k in d and d[k] is not None:
            return d[k]
    return default


def parse_dt(value):
    """Best-effort parse of a timestamp that may already be a datetime
    (PyYAML auto-parses ISO8601 strings) or a plain string."""
    if value is None:
        return None
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    if isinstance(value, str):
        try:
            dt = datetime.fromisoformat(value.replace("Z", "+00:00"))
            return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)
        except ValueError:
            return None
    return None


def fmt_dt(dt):
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC") if dt else "?"


def fmt_duration(aos, los):
    if not (aos and los):
        return "?"
    secs = int((los - aos).total_seconds())
    m, s = divmod(max(secs, 0), 60)
    return f"{m}m{s:02d}s"


def main():
    import station
    station.enter()
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--path", default="schedule.yaml", help="path to schedule.yaml")
    ap.add_argument("--all", action="store_true",
                     help="show every pass, not just approved ones")
    args = ap.parse_args()

    try:
        with open(args.path) as f:
            schedule = yaml.safe_load(f)
    except FileNotFoundError:
        print(f"'{args.path}' not found. Run plan_passes.py first to generate it.",
              file=sys.stderr)
        sys.exit(1)

    capable_norads = set()
    try:
        with open("satellites.yaml") as f:
            sat_cfg = yaml.safe_load(f)
        from edit_satellite import record_iq_capable
        capable_norads = {s["norad"] for s in sat_cfg.get("satellites", [])
                           if record_iq_capable(s)}
    except FileNotFoundError:
        pass  # record_iq column still shows; capability just can't be checked

    if not schedule or "passes" not in schedule:
        print(f"'{args.path}' has no 'passes' key - nothing to show.", file=sys.stderr)
        sys.exit(1)

    passes = schedule["passes"]
    if not args.all:
        passes = [p for p in passes if p.get("approved")]

    if not passes:
        which = "approved " if not args.all else ""
        print(f"No {which}passes found in {args.path}.")
        return

    SAT_KEYS = ["sat", "satellite", "name", "sat_name"]
    AOS_KEYS = ["aos", "aos_dt", "aos_time", "start"]
    LOS_KEYS = ["los", "los_dt", "los_time", "end"]
    ELEV_KEYS = ["max_elevation_deg", "max_elevation", "max_el", "elevation", "el_max"]

    enriched = []
    for p in passes:
        sat = get_first(p, SAT_KEYS, "?")
        aos = parse_dt(get_first(p, AOS_KEYS))
        los = parse_dt(get_first(p, LOS_KEYS))
        elev = get_first(p, ELEV_KEYS)
        enriched.append((aos, los, sat, elev, p))

    # sort by AOS; passes with unparseable AOS sink to the bottom
    enriched.sort(key=lambda t: (t[0] is None, t[0]))

    now = datetime.now(timezone.utc)
    next_shown = False

    # paired passes (see pair_passes.py): who rides with whom. The column only appears when
    # something in the queue is paired, so an unpaired queue prints exactly as it always did.
    ref = lambda r: f"{r.get('norad')}@{r.get('aos')}"
    name_of = {ref(t[4]): t[2] for t in enriched}
    riders = {}
    for t in enriched:
        if t[4].get("rides_with"):
            riders.setdefault(t[4]["rides_with"], []).append(t[2])
    any_pairs = bool(riders)
    width = 99 + (30 if any_pairs else 0)
    print(f"{'STATUS':13s} {'SATELLITE':12s} {'AOS':22s} {'LOS':22s} {'DUR':8s} {'MAX EL':7s} {'RECORD_IQ':10s}"
          + (" TOGETHER" if any_pairs else ""))
    print("-" * width)

    for aos, los, sat, elev, raw in enriched:
        if los and los < now:
            status = "past"
        elif aos and aos <= now <= (los or aos):
            status = "ACTIVE"
        elif not next_shown and aos and aos > now:
            status = "NEXT"
            next_shown = True
        else:
            status = "upcoming"

        if not raw.get("approved", True) and args.all:
            status = "(unapproved)"

        elev_str = f"{elev:.0f}deg" if isinstance(elev, (int, float)) else "?"
        if raw.get("norad") not in capable_norads:
            iq_str = "n/a"
        elif "record_iq" not in raw:
            iq_str = "(default)"
        else:
            iq_str = "ON" if raw["record_iq"] else "OFF"
        together = ""
        if any_pairs:
            if raw.get("rides_with"):
                together = f" rides with {name_of.get(raw['rides_with'], '?')}"
            elif ref(raw) in riders:
                together = f" steers beam, with {', '.join(riders[ref(raw)])}"
        print(f"{status:13s} {sat:12s} {fmt_dt(aos):22s} {fmt_dt(los):22s} "
              f"{fmt_duration(aos, los):8s} {elev_str:7s} {iq_str:10s}{together}")

    total = len(enriched)
    remaining = sum(1 for aos, los, *_ in enriched if aos and aos > now)
    print("-" * width)
    print(f"{total} pass(es) shown, {remaining} still upcoming.")


if __name__ == "__main__":
    main()
